OCAMLMAKEFILE = ./OCamlMakefile

SOURCES := netencoding.mli       netencoding.ml        \
           cgi.mli               cgi.ml                \
                                 basics.ml             \
                                 common.ml             \
           formlets.mli          formlets.ml           \
           formlets_contexts.mli formlets_contexts.ml  \
           formlets_typed.mli    formlets_typed.ml     

RESULT := formlets

LIBS := str

all: bcl ncl

include $(OCAMLMAKEFILE)
